config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'authors#index'
  resources :authors
      # get '/authors', to: 'authors#index'
      # get '/authors/new', to: 'authors#new'
      # get '/authors/:id', to: 'authors#show'
      # post '/authors', to: 'authors#create'
      # get '/authors/:id/edit', to: 'authors#edit'
      # patch '/authors/:id', to: 'authors#update'
      # delete '/authors/:id', to: 'authors#destroy'
  resources :books, except: [:new, :create]
      # get '/books', to: 'books#index'
      # get '/books/:id', to: 'books#show'
      # get '/books/:id/edit', to: 'books#edit'
      # post '/books/:id', to: 'books#update'
      # delete '/books/:id', to: 'books#destroy'
  
  get '/authors/:id/books', to: 'authors_books#index'
  get '/authors/:id/books/new', to: 'authors_books#new'
  post '/authors/:id/books', to: 'authors_books#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord

    validates :name, presence: true
    validates :age, presence: true, numericality: true
    validates :alive, inclusion: { in: [true, false] }
    
    has_many :books, dependent: :destroy

    def self.order_created
        order(created_at: :desc)
    end

    def self.order_book_count
        
        # binding.pry
        
        # I know this is ruby :(
        # all.sort { |a, b| b.books.count <=> a.books.count   } 
        Author.find_by_sql(
        "SELECT * FROM authors
        LEFT OUTER JOIN
        (select author_id, count(*) as book_count from books group by author_id)as tmp_count on(id = author_id)
        ORDER BY COALESCE(book_count,0) desc;")  
        
        # left_joins(:books).group(:id).order('COUNT(books.id) DESC')
     end
    

    def book_count
        books.count
    end

    def alphabetize(sort)
        books.alphabetize_books(sort)
    end
    
end

app/models/book.rb
class Book < ApplicationRecord
    
    validates :title, presence: true
    validates :page_count, presence: true, numericality: true
    validates :fiction, inclusion: { in: [true, false]}
    
    belongs_to :author

    def self.alphabetize_books(sort)
        sort == 'true' ? order(:title) : Book.all
    end

    def self.page_max(max)
        where("page_count <= ?", max)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_books_controller.rb
class AuthorsBooksController < ApplicationController
    def index
        @author = Author.find(params[:id])
    end

    def new
        @author = Author.find(params[:id])
    end

    def create
        author = Author.find(params[:id])
        book = author.books.create(book_params)
        redirect_to "/authors/#{author.id}/books"
    end

    private

        def book_params
            params.permit(:title, :page_count, :fiction, :author_id)
        end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

    def index
        @authors = Author.order_created
    end

    def show
        @author = Author.find(params[:id])
    end
    
    def new
    
    end
    
    def create
        @author = Author.create(author_params)
        redirect_to authors_path
    end

    def edit
        @author = Author.find(params[:id])
    end

    def update
        author = Author.find(params[:id])
        author.update(author_params)
        redirect_to "/authors/#{author.id}"
    end

    def destroy
        Author.destroy(params[:id])
        redirect_to authors_path
    end
    
    
    private

        def author_params
            params.permit(:name, :age, :alive)
        end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController 
    def index
        @books = Book.where(fiction: true)
    end

    def show
        @book = Book.find(params[:id])
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        book = Book.find(params[:id])
        book.update(book_params)
        redirect_to "/books/#{book.id}"
    end

    def destroy
        Book.destroy(params[:id])
        redirect_to "/books"
    end
    
    
    private

        def book_params
            params.permit(:title, :page_count, :fiction)
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/edit.html.erb
<h1>Edit Author</h1>
<%= form_with url: "/authors/#{@author.id}", method: :patch, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <%= f.label :alive %>
  <%= f.check_box :alive %>
  <%= f.submit "Submit"%>
<% end %>

app/views/authors/index.html.erb
<h1>List of Authors</h1>

<% if params[:book_count] == 'true' %>
    <% @authors.order_book_count.each do |author| %>
        <div id="author-<%= author.name %>">
            <h3><%= author.name %></h3>
            <h3>Book Count: <%= author.book_count %></h3>
            <p>Added: <%= author.created_at %></p>
            <p><%= link_to "Visit #{author.name} Show Page", "/authors/#{author.id}"%></p>
            <p><%= link_to "Update #{author.name}", "/authors/#{author.id}/edit", method: :get %></p>
            <p><%= link_to "Delete #{author.name}", "/authors/#{author.id}", method: :delete %></p><hr>
        </div>
    <% end %>
<% else %>
    <% @authors.each do |author| %>
        <div id="author-<%= author.name %>">
            <h3><%= author.name %></h3>
            <h3>Book Count: <%= author.book_count %></h3>
            <p>Added: <%= author.created_at %></p>
            <p><%= link_to "Visit #{author.name} Show Page", "/authors/#{author.id}"%></p>
            <p><%= link_to "Update #{author.name}", "/authors/#{author.id}/edit", method: :get %></p>
            <p><%= link_to "Delete #{author.name}", "/authors/#{author.id}", method: :delete %></p><hr>
        </div>
    <% end %>
<% end %>

<%= link_to "Order Authors By Book Count", "/authors?book_count=true" %><br>
<%= link_to "New Author", "/authors/new" %>

app/views/authors/new.html.erb
<h1>Add New Author</h1>
<%= form_with url: "/authors", method: :post, local: true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :age %>
    <%= f.text_field :age %><br>
    <%= f.label :alive %>
    <%= f.check_box :alive %><br>
    <%= f.submit 'Submit'%>
<% end %>

app/views/authors/show.html.erb
<h1>Show Page</h1>

<h3>Name: <%= @author.name %></h3>
<h3>Age: <%= @author.age %></h3>
<h3>Alive: <%= @author.alive %></h3>
<h3>Book Count: <%= @author.book_count %></h3>
<h3><%= link_to "View Authors Books", "/authors/#{@author.id}/books", method: :get %></h3>
<h3><%= link_to "Update Author", "/authors/#{@author.id}/edit", method: :get %></h3>
<h3><%= link_to "Delete Author", "/authors/#{@author.id}", method: :delete %></h3>

app/views/authors_books/index.html.erb
<h1><%= @author.name %>'s Book Show Page</h1>

<h3>Books</h3><hr>

<% @author.alphabetize(params[:alpha]).each do |book| %>
    <% if params[:page_limit].nil? %>
        <p>Title: <%= book.title %></p>
        <p>Page Count: <%= book.page_count %></p>
        <p>Fiction: <%= book.fiction %></p><hr>
    <% elsif book.page_count <= params[:page_limit].to_i %>
        <p>Title: <%= book.title %></p>
        <p>Page Count: <%= book.page_count %></p>
        <p>Fiction: <%= book.fiction %></p><hr>
    <% end %>
<% end%>

<%= form_with url:"/authors/#{@author.id}/books?limit=true", method: :get, local: true do |f| %>
    <%= f.label "Set Page Limit:" %>
    <%= f.number_field :page_limit %>
    <%= f.submit "Filter" %>
<% end%>

<%= link_to "Alphabetize Books", "/authors/#{@author.id}/books?alpha=true" %>
<%= link_to "Add New Book", "/authors/#{@author.id}/books/new" %>

app/views/authors_books/new.html.erb
<h1>Add New Book</h1>
<%= form_with url: "/authors/#{@author.id}/books" , method: :post, local: true do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br>
    <%= f.label :page_count %>
    <%= f.text_field :page_count %><br>
    <%= f.label :fiction %>
    <%= f.text_field :fiction %><br>
    
    <%= f.submit 'Submit'%>
<% end %>

app/views/books/edit.html.erb
<h1>Edit <%= "#{@book.title}" %></h1>

<%= form_with url:"/books/#{@book.id}", method: :patch, local: true do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :page_count %>
    <%= f.text_field :page_count %>
    <%= f.label :fiction %>
    <%= f.check_box :fiction %>
    
    <%= f.submit 'Submit' %>
<% end%>

app/views/books/index.html.erb
<h1>Books Homepage</h1>
<h3>All Books</h3><hr>
<% @books.each do |book| %>
    <p>Title: <%= book.title %></p>
    <p>Page Count: <%= book.page_count %></p>
    <p>Fiction: <%= book.fiction %></p>
    <p><%= link_to "Update #{book.title}", "/books/#{book.id}/edit" %></p>
    <p><%= link_to "Delete #{book.title}", "/books/#{book.id}", method: :delete %></p><hr>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %> Show Page</h1>

<h3>Title: <%= @book.title %></h3>
<h3>Page Count: <%= @book.page_count %></h3>
<h3>Fiction: <%= @book.fiction %></h3>
<h3><%= button_to "Update", "/books/#{@book.id}/edit", method: :get %></h3>
<h3><%= button_to "Delete Book", "/books/#{@book.id}", method: :delete %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthorList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= link_to "All Authors", authors_path %>
    <%= link_to "All Books", books_path %>
    <%= yield %>
  </body>
</html>